version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - ./backend/uploaded_images:/app/uploaded_images
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://yourusername:yourpassword@db:5432/yourdatabase

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - eslint_cache:/usr/src/app/.eslintcache
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ESLINT_NO_DEV_ERRORS=true
    user: "node"

volumes:
  postgres_data:
  eslint_cache: